name: smoke test

on: push

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: "3.10.0"

    - name: Install poetry
      run: |
        python -m pip install poetry
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
        source $HOME/.poetry/env

    - name: Install project deps
      run: |
        cd colosseum
        poetry install

    - name: Run smoke test
      run: |
        cd colosseum
        poetry run python ../skirmish.py \
          ../agents/dummy_agent.py \
          ../agents/food_catcher_exterminator.py \
          ../agents/food_catcher_replicator.py \
          ../agents/food_catcher_take_first_food.py \
          ../agents/food_catcher_take_nearest_food.py
