name: Agent smoke test

on: push

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: "3.10.0"

    - name: Install poetry
      run: |
        python -m pip install poetry
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
        source $HOME/.poetry/env

    - name: Install project deps
      run: |
        poetry install

    - name: Run smoke test
      run: |
        git clone https://github.com/h3nnn4n/colosseum_agents
        poetry run python skirmish.py \
          colosseum_agents/food_catcher/rusher/agent.py \
          colosseum_agents/food_catcher/exterminator/agent.py \
          colosseum_agents/food_catcher/dummy/agent.py \
          colosseum_agents/food_catcher/first/agent.py
        poetry run python skirmish.py \
          colosseum_agents/food_catcher/nearest/agent.py \
          colosseum_agents/food_catcher/first/agent.py \
          colosseum_agents/food_catcher/first/agent.py \
          colosseum_agents/food_catcher/dummy/agent.py
