name: Deploy

on: push
#on:
  #push:
    #branches:
      #- production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: "h3nnn4n/colosseum_infra"

      - name: Setup ssh
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts

      - name: Install requirements
        run: |
          cd ansible
          ansible-galaxy install -r requirements.yml

      - name: Deploy
        run: |
          cd ansible
          ansible-playbook -i production.yml colosseum_workers.yml --tags colosseum_worker
        env:
          VAULT_PASSWORD: "${{ secrets.VAULT_PASSWORD }}"
